version: '3.8'
services:
  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
      - ./database:/usr/src/app/database
    command: npm run start:prod
