name: Docker Build and Deploy

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Images
        run: |
          cd server
          docker-compose build
          docker-compose push

  deploy:
    needs: build
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Deploy to EC2
        uses: appleboy/ssh-action@master
        with:
          host: ec2-13-59-11-229.us-east-2.compute.amazonaws.com
          username: ec2-user
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Navegue para o diretório onde docker-compose.yml está localizado
            cd server
            # Puxe as últimas imagens
            sudo docker-compose pull
            # Derrube os containers atuais e remova volumes
            sudo docker-compose down --volumes --remove-orphans
            # Inicie os containers com as novas imagens
            sudo docker-compose up -d
            # Remova as imagens não utilizadas
            sudo docker image prune -f